// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearChatHistory() {
  return window['go']['main']['WailsApp']['ClearChatHistory']();
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WailsApp']['Connect'](arg1, arg2, arg3, arg4);
}

export function DeleteHistory(arg1, arg2) {
  return window['go']['main']['WailsApp']['DeleteHistory'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['WailsApp']['Disconnect']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['WailsApp']['GetChatHistory'](arg1);
}

export function GetConfig() {
  return window['go']['main']['WailsApp']['GetConfig']();
}

export function GetHistory() {
  return window['go']['main']['WailsApp']['GetHistory']();
}

export function SendMessage(arg1) {
  return window['go']['main']['WailsApp']['SendMessage'](arg1);
}
