// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearChatHistory():Promise<void>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function DeleteHistory(arg1:string,arg2:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetChatHistory(arg1:string):Promise<Array<main.ChatMessage>>;

export function GetConfig():Promise<Record<string, string>>;

export function GetHistory():Promise<Array<main.ConnectionRecord>>;

export function SendMessage(arg1:string):Promise<string>;
